name: GitHub Actions Demo
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**' # Exclude changes in the .github folder
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0' # Every Sunday at 6:15 UTC
  workflow_dispatch: # Manual trigger

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Tests
        run: echo "Running tests..."
      - name: Deploy App
        if: success() # Only deploy if tests succeed
        run: echo "Deploying app..."
